### ISSUE TITLE
dicts cannot be checked with equal if key doesn't support <

### ISSUE THREAD

**Issue by damonmaria** [gabrielfalcao/sure#148]
## Issue Type

Please specify the type of the issue you want to submit:

- [X] Bug Report
- [ ] Feature Request
- [ ] Documentation Report
- [ ] General Enhancement Idea
- [ ] ...

## Versions & Configuration

Please specify the following things:

- version of `sure`: 1.4.11
- implementation and version of python: `Python 3.6.5 (default, Mar 30 2018, 06:41:53) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin`
- operating system: MacOS 10.13.5

## Steps to reproduce (Expected and Actual Results)

```python
import sure
from enum import Enum

class SomeEnum(Enum):
    A = 'A'
    B = 'B'

{SomeEnum.A: 0, SomeEnum.B: 1}.should.equal({SomeEnum.A: 0, SomeEnum.B: 1})
```

Results in: `TypeError: '<' not supported between instances of 'SomeEnum' and 'SomeEnum'`

This should return `True`, and it does if the `dict` only has one item.

**Comment by timofurrer** [comment]
The problem is that the dictionary keys are sorted before comparing them: 

https://github.com/gabrielfalcao/sure/blob/8928dd0c014d087cc342ec3d5b1beb71a219a7fc/sure/core.py#L109

This is a problem if the key type is not sortable. 
It's necessary because if the two dicts are not equal using `X == Y`, then a deep comparison is performed which need the keys to be sorted:

https://github.com/gabrielfalcao/sure/blob/8928dd0c014d087cc342ec3d5b1beb71a219a7fc/sure/core.py#L132

However, I think we can work around that, because from line 114 to 126 is already verified that the two dicts have the same keys, so the loop on 132 could just iterate the keys from the lhs dict in the given order and compare against the one on the rhs.

I hope I can provide a fix later today.
