### ISSUE TITLE
Fix tests on pypy (+enable testing on travis-ci)

### ISSUE THREAD

**Issue by domenkozar** [gabrielfalcao/sure#64]

**Comment by msabramo** [comment]
:+1 
I discovered this because pip uses freezegun  and freezegun uses should.

**Comment by timofurrer** [comment]
One of the essential dependencies of sure is `forbiddenfruit` (https://github.com/clarete/forbiddenfruit). This package allows you to patch built-in objects in **cpython**. Thus, pypy and other python implementations won't work because the C API is not given.
Unfortunately, I haven't discovered any solution for that in pypy (Do you guys know an existing one?) ... Someone has to write something like that.

**Comment by timofurrer** [comment]
I just merged #90 which brings pypy support and adds it to the test matrix, too.
