### ISSUE TITLE
Can test-requirements be unpinned please?

### ISSUE THREAD

**Issue by xnox** [gabrielfalcao/sure#75]
Can test-requirements be unpinned? e.g. use >=, rather than ==? There is a newer release of sure at least.

**Comment by timofurrer** [comment]
I think for the `requirements.txt` and `development.txt` it's best to specify the dependencies with a certain version, like `sure==1.0.0` because everyone should develop with the same versions!
For the `setup.py` you should use `!=`, `>=` etc. to provide a best flexibility for the end user.

**Comment by xnox** [comment]
It's extremely difficult to package software in distributions. Because whilst this project develops against this particular version, others do not. Surely, one would want to test/integrate/migrate to the widest range of dependencies possible. Note, i specifically asked about test-requirements, rather than anything else.

**Comment by timofurrer** [comment]
I didn't really get what you try to point out. 
Usually you are developing with virtualenvs, right (or tox, ...)? So there should not be a problem with pinned dependencies... Actually you'll have less problems, because everyone who's developing is using the same versions which prevents confusions. If you want to upgrade a requirement just make sure everything works and submit a PR.

**Comment by xnox** [comment]
I work on a distribution, e.g. clearlinux, debian, ubuntu. Those do not use virtuenv, as they provide the full distro in a system namespace. Ok, i'll upgrade the requirements and submit a PR.

**Comment by timofurrer** [comment]
All requirements which are used by setuptools/pip are unpinned anyway. So I don't think there should be big issues fix the system packages. (Unless there is an incompatibility between sure and the system packages because they are not pinned).

However, I've just upgraded the requirements to the newest versions. 
Is there anything else related to this issue you are concerned about?
If not, I'd like to close this one @xnox
