### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by timofurrer** [gabrielfalcao/sure#91]
This is mainly a question for @gabrielfalcao 
Where do you see this project going? There are a lot of issues and some pull requests which need some work. I really appreciate this package and I'm using it in several private projects and at work - as probably others too. Some of the issues and pull request are very appreciable for the projects I am using sure.
If you do not have time to maintain this project any more: I'm sure there are people here who would help (including me).

:beers:

**Comment by timofurrer** [comment]
ping

**Comment by gabrielfalcao** [comment]
Hey man, I have plans to improve certain parts of the project and do a bit of code cleanup.

Here are my short-term goals for it:

* Migrate all the docs to sphinx, document and add examples for each use case
* Blog tutorials and create screencasts to showcase the **ideal** usage of sure.

Mid-term goals:

* Create a DSL that allows describing tests in a more fluent, rspec fashion (i.e: `describe()`, `given()`, `when()`, `then()`)
* Create a test runner that can find tests written with the special DSL and give a nice output.

I'll go over the pull requests now and apply the ones that makes sense.
But since this project is so so core in any application (basically if the assertions are buggy, your whole code that depends on tests becomes unreliable), I will give my personal full attention to it, and I'll make sure to do house keeping before applying pull requests (as a matter of fact I've carelessly trusted PR's for sure, HTTPrettty and lettuce and they broke the project)

**Comment by timofurrer** [comment]
Thanks for the statement. I really appreciate it and I fully understand your opinion and concerns!
I'm willing to help make this project better. How would you feel about creating issues for all the ideas you have in mind? Maybe introduce labels like `ready-to-take` or similar.. 
It would make collaboration much easier.

**Comment by jamesfe** [comment]
@gabrielfalcao - I'd love to help too.  Willing to look the current issues in the tracker and triage and take some on.

**Comment by gabrielfalcao** [comment]
@timofurrer I'm gonna take time this weekend to write down some ideas in form of tickets.
Thank you **SO MUCH** for be willing to write so much code :+1:

**Comment by timofurrer** [comment]
@gabrielfalcao  That's awesome. I really appreciate your time!

**Comment by timofurrer** [comment]
@gabrielfalcao any news?

**Comment by meijdenmedia** [comment]
What is the status on this one? Any more news?

**Comment by timofurrer** [comment]
Hi all,

@gabrielfalcao added me as a collaborator to this project. I'll take care of it as good as I can. 

The following things will be addressed first:

- [ ] Cleanup Issue and PR backlog
- [ ] Fix (urgent) bugs.
- [ ] Merge low-hanging-fruit PRs. 
- [ ] Create timeline for further ideas
- [ ] Ensure python 2 and python 3 compatibility and communicate which versions are tested

... For any additional ideas/suggestions please open an issue.

More contributions are always more then welcome!

Thanks to @gabrielfalcao again :beers:

**Comment by gabrielfalcao** [comment]
I'm excited about this!
